"""resync migrations

Revision ID: 38393452ab22
Revises: 0bbabc75dfa7
Create Date: 2025-02-15 17:41:11.279493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38393452ab22'
down_revision = '0bbabc75dfa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prova',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('climate', sa.String(length=80), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('terrain', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prova')
    # ### end Alembic commands ###
