"""empty message

Revision ID: a8abc6f9fe2c
Revises: c689059489c0
Create Date: 2025-02-17 23:20:17.364038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8abc6f9fe2c'
down_revision = 'c689059489c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('people_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('planet_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.alter_column('planet_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('people_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
